In [1]:
import numpy as np
import pandas as pd

from pandas import DataFrame, Series

In [2]:
# Set some pandas options
pd.set_option('display.notebook_repr_html', True)
pd.set_option('display.max_columns', 1000)
pd.set_option('display.max_rows', 1000)

In [5]:
coords_df = pd.read_csv('data/coordinates.csv', names=['ID', 'Loc_Id', \
                                                'Type', 'Long', 'Lat', 'Name'])

mosque_df = pd.read_csv('data/mosques_data.csv', names =['ID', 'Loc_ID', 'Type', 'Value', 'Name', 'Nickname'])

In [6]:
mosque_df.head(10)

     ID  Loc_ID     Type  Value                       Name   Nickname
0  5000       3  mosques    391             Bukhāra (city)    Bukhara
1  5002      46  mosques    715       Ghijduwān
Kharqānrūd  Ghijduwan
2  5005      52  mosques    254  Zinda-nay
Khitfar
Pīshkūh        NaN
3  5007      54  mosques    311   Janūbī Rūd
Tūmān-i Mazār        NaN
4  5008      55  mosques    481                Shamālī Rūd        NaN
5   103      47  mosques    418           Qarākūl
Qorako‘l    Qarakol
6   108     308  mosques      7        Qurghan-i Ghijduvan        NaN
7  3312      49  mosques    180                    Pīrmast    Pirmast
8  3318      51  mosques    244             Rāmītan
Sāmjan    Ramitan